Upgraded Gradle Wrapper to 8.1.1
britter/maven-plugin-development pull request #94
Opened 2023-05-03 11:31 UTC by nulls

### What's done:
- updated gradle wrapper
- supported changes in build.gradle.kts
- updated java8.lock by `:plugin:stutterWriteLocks`
- changed input parameters for tasks, because Gradle 8.x cannot serialize FileCollection and Configuration

2023-05-05 11:26 UTC, britter commented
Hey @nulls, thank you for the PR. Is this something you need included or just build hygene? Asking because I'm considering moving the plugin to https://github.com/gradlex-org and that would include kind of a rewrite anyways.

2023-05-05 12:02 UTC, nulls commented
Hi @britter, 
Our project [diktat](https://github.com/saveourtool/diktat) uses this plugin and we are upgrading the Gradle version in the project.
It would be great if it will be included.

Btw, I see that `Sample Project Build` does fail. I guess it's okay till a new version is released, isn't it?

2023-05-08 15:56 UTC, britter commented
@nulls okay, I see. I'll have a look into this on the weekend. Unfortunately I think we need to do this differently in order to keep compatibility with released versions.

2023-05-21 08:23 UTC, britter commented
@nulls sorry to keep you waiting. This is next on my backlog. I hope to find some time the coming week to merge and release this.

2023-06-04 11:03 UTC, britter requested changes
Hey @nulls! Finally got to reviewing this. I think the problem are not the types of the inputs but their annotations. Can you please try if changing them the way I've pointed out makes it work on Gradle 8? That way we can leave the types as they are and don't break binary compat.

2023-06-05 10:06 UTC, nulls commented on subprojects/plugin/src/main/kotlin/de/benediktritter/maven/plugin/development/task/GenerateMavenPluginDescriptorTask.kt
> +    abstract val sourcesDirs: SetProperty<File>
applied

2023-06-05 10:06 UTC, nulls commented on subprojects/plugin/src/main/kotlin/de/benediktritter/maven/plugin/development/task/AbstractMavenPluginDevelopmentTask.kt
> +    abstract val runtimeDependenciesConfigurationName: Property<String>
applied

2023-06-05 19:50 UTC, britter approved these changes
Awesome, thank you!

2023-06-05 19:51 UTC, merged

2023-06-05 20:59 UTC, britter commented
@nulls I've released 0.4.2 which contains your fix. Please give it a try!

2023-06-06 09:53 UTC, nulls commented
> @nulls I've released 0.4.2 which contains your fix. Please give it a try!

Thanks, now it does work!